#!/usr/bin/env python

import sys
import tiktoken

content = sys.stdin.read()

model = "gpt-3.5-turbo-0301"

try:
    encoding = tiktoken.encoding_for_model(model)
except KeyError:
    encoding = tiktoken.get_encoding("cl100k_base")

print(len(encoding.encode(content)))
